import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ResumeArea from '../components/ResumeArea'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Matthew Sweet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResumeArea />
    </>
  )
}

export default Home
